/user/add:
  controller: "User"
  action: "register"
  
/user/registerbd:
  controller: "User"
  action: "registerbd"

/user/login:
  controller: "User"
  action: "login"

/user/loginbd:
  controller: "User"
  action: "loginbd"

/user/home:
  controller: "User"
  action: "home"

/se-connecter:
  controller: "User"
  action: "login"


/se-deconnecter:
  controller: "User"
  action: "logout"

/backoffice:
  controller: "Backoffice"
  action: "dashboard"

/page:
  controller: "page"
  action: "show"

/connection-validator:
  controller: "User"
  action: "connection"

/dashboard:
  controller: "page"
  action: "dashboard"